<?php

define('ATTIKA_RESTAURANT_VERSION', '1.0.2');
define('ATTIKA_RESTAURANT_ABS_PATH', dirname(__FILE__));
define('ATTIKA_RESTAURANT_REL_PATH', dirname(plugin_basename(__FILE__ )));
define('ATTIKA_RESTAURANT_URL_PATH', plugin_dir_url( __FILE__ ));
define('ATTIKA_RESTAURANT_ASSETS_PATH', ATTIKA_RESTAURANT_ABS_PATH.'/assets');
define('ATTIKA_RESTAURANT_ASSETS_URL_PATH', ATTIKA_RESTAURANT_URL_PATH.'assets');
define('ATTIKA_RESTAURANT_CPT_PATH', ATTIKA_RESTAURANT_ABS_PATH.'/post-types');
define('ATTIKA_RESTAURANT_SHORTCODES_PATH', ATTIKA_RESTAURANT_ABS_PATH.'/modules/shortcodes');